version: '3'
services:
  my_postgres_container:
    image: postgres:latest
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: himanshu
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - my_postgres_container
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  pgdata:
